services:
  graze-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruminantia-graze
    restart: unless-stopped
    volumes:
      - graze-output:/app/output
      - ./config.ini:/app/config.ini:ro
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import requests; requests.get('https://www.reddit.com/r/worldnews.json', timeout=30)",
        ]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 2m
    networks:
      - graze-network

volumes:
  graze-output:
    driver: local

networks:
  graze-network:
    driver: bridge
